POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "How to program",
  "author": "Jiminy Cricket",
  "url": "http://localhost.com",
  "likes": 44,
  "user": "643a842525823bf4afb2843d"
}

###

POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "Dance",
  "author": "Timon",
  "url": "http://suomi.fi",
  "likes": 23,
  "user": "643a849c25823bf4afb28445"
}

###

POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "name": "Christopher"
}

###

POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "number": "058736482"
}

###

POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
}
