POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "the_senate",
    "name": "Sheev Palpatine",
    "password": "nonHashedPassword"
}

###

POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "bob",
    "password": "nonHashedPassword"
}

###

POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "name": "Sheev Palpatine",
    "password": "scn392rh4rjb"
}

###

POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "the_senate",
    "password": "scn392rh4rjb"
}

###

POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "the_senate",
    "name": "Sheev Palpatine"
}

###

POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "the_senate",
    "name": "Sheev Palpatine",
    "password": null
}
