name: Lint and test NodeJS fullStackOpen exercises

on: pull_request

permissions:
  contents: read

jobs:
  build:
    name: Node project ${{ matrix.directories }}

    runs-on: ubuntu-latest

    strategy:
      matrix: { directories: ["part4"] }

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies for ${{ matrix.directories }}
        run: npm ci
        working-directory: ${{ matrix.directories }}
      - name: Lint ${{ matrix.directories }}
        run: npm run lint
        working-directory: ${{ matrix.directories }}
    #   - name: Run ${{ matrix.directories }} tests
    #     run: npm test --verbose --maxWorkers=1
    #     working-directory: ${{ matrix.directories }}
